runtime: python39

handlers:
  - url: /static
    static_dir: staticfiles/
  - url: /.*
    secure: always
    script: auto

env_variables:
  APPENGINE_URL: 'https://boilerplate-django-vue-gae.de.r.appspot.com/'
  GOOGLE_CLOUD_PROJECT: '146920878707'
  SETTINGS_NAME: 'django_settings'
  BUCKET_NAME: 'boilerplate-django-vue-gae.appspot.com'
service_account: boilerplate-django-vue-gae@appspot.gserviceaccount.com
service: default
